// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjjwgsvbjjtflyziohnn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqandnc3Ziamp0Zmx5emlvaG5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NjQ5MjcsImV4cCI6MjA2MjQ0MDkyN30.AkaZJCZD9UTDYikqWKMDaLngR2Mb1ceRMXn0dv3PYUA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);